// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cashpack.model;

import br.com.cashpack.model.UsuarioCashPackDataOnDemand;
import br.com.cashpack.model.UsuarioCashPackIntegrationTest;
import br.com.cashpack.service.UsuarioCashPackService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuarioCashPackIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsuarioCashPackIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsuarioCashPackIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UsuarioCashPackIntegrationTest: @Transactional;
    
    @Autowired
    UsuarioCashPackDataOnDemand UsuarioCashPackIntegrationTest.dod;
    
    @Autowired
    UsuarioCashPackService UsuarioCashPackIntegrationTest.usuarioCashPackService;
    
    @Test
    public void UsuarioCashPackIntegrationTest.testCountAllUsuarioCashPacks() {
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", dod.getRandomUsuarioCashPack());
        long count = usuarioCashPackService.countAllUsuarioCashPacks();
        Assert.assertTrue("Counter for 'UsuarioCashPack' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsuarioCashPackIntegrationTest.testFindUsuarioCashPack() {
        UsuarioCashPack obj = dod.getRandomUsuarioCashPack();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to provide an identifier", id);
        obj = usuarioCashPackService.findUsuarioCashPack(id);
        Assert.assertNotNull("Find method for 'UsuarioCashPack' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UsuarioCashPack' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsuarioCashPackIntegrationTest.testFindAllUsuarioCashPacks() {
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", dod.getRandomUsuarioCashPack());
        long count = usuarioCashPackService.countAllUsuarioCashPacks();
        Assert.assertTrue("Too expensive to perform a find all test for 'UsuarioCashPack', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UsuarioCashPack> result = usuarioCashPackService.findAllUsuarioCashPacks();
        Assert.assertNotNull("Find all method for 'UsuarioCashPack' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UsuarioCashPack' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsuarioCashPackIntegrationTest.testFindUsuarioCashPackEntries() {
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", dod.getRandomUsuarioCashPack());
        long count = usuarioCashPackService.countAllUsuarioCashPacks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UsuarioCashPack> result = usuarioCashPackService.findUsuarioCashPackEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UsuarioCashPack' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UsuarioCashPack' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsuarioCashPackIntegrationTest.testFlush() {
        UsuarioCashPack obj = dod.getRandomUsuarioCashPack();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to provide an identifier", id);
        obj = usuarioCashPackService.findUsuarioCashPack(id);
        Assert.assertNotNull("Find method for 'UsuarioCashPack' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsuarioCashPack(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UsuarioCashPack' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsuarioCashPackIntegrationTest.testUpdateUsuarioCashPackUpdate() {
        UsuarioCashPack obj = dod.getRandomUsuarioCashPack();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to provide an identifier", id);
        obj = usuarioCashPackService.findUsuarioCashPack(id);
        boolean modified =  dod.modifyUsuarioCashPack(obj);
        Integer currentVersion = obj.getVersion();
        UsuarioCashPack merged = (UsuarioCashPack)usuarioCashPackService.updateUsuarioCashPack(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UsuarioCashPack' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsuarioCashPackIntegrationTest.testSaveUsuarioCashPack() {
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", dod.getRandomUsuarioCashPack());
        UsuarioCashPack obj = dod.getNewTransientUsuarioCashPack(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UsuarioCashPack' identifier to be null", obj.getId());
        try {
            usuarioCashPackService.saveUsuarioCashPack(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UsuarioCashPack' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsuarioCashPackIntegrationTest.testDeleteUsuarioCashPack() {
        UsuarioCashPack obj = dod.getRandomUsuarioCashPack();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioCashPack' failed to provide an identifier", id);
        obj = usuarioCashPackService.findUsuarioCashPack(id);
        usuarioCashPackService.deleteUsuarioCashPack(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'UsuarioCashPack' with identifier '" + id + "'", usuarioCashPackService.findUsuarioCashPack(id));
    }
    
}
