// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cashpack.model;

import br.com.cashpack.model.Gerente;

privileged aspect Gerente_Roo_JavaBean {
    
    public String Gerente.getCodigo() {
        return this.codigo;
    }
    
    public void Gerente.setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
}
