// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cashpack.model;

import br.com.cashpack.model.Gestor;
import javax.persistence.Entity;

privileged aspect Gestor_Roo_Jpa_Entity {
    
    declare @type: Gestor: @Entity;
    
}
