// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cashpack.model;

import br.com.cashpack.model.RamoDeAtividade;

privileged aspect RamoDeAtividade_Roo_JavaBean {
    
    public String RamoDeAtividade.getNome() {
        return this.nome;
    }
    
    public void RamoDeAtividade.setNome(String nome) {
        this.nome = nome;
    }
    
}
