// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cashpack.model;

import br.com.cashpack.model.UsuarioAdministrador;

privileged aspect UsuarioAdministrador_Roo_JavaBean {
    
    public String UsuarioAdministrador.getNome() {
        return this.nome;
    }
    
    public void UsuarioAdministrador.setNome(String nome) {
        this.nome = nome;
    }
    
}
