// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cashpack.model;

import br.com.cashpack.model.UsuarioAdministrador;
import javax.persistence.Entity;

privileged aspect UsuarioAdministrador_Roo_Jpa_Entity {
    
    declare @type: UsuarioAdministrador: @Entity;
    
}
